# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ws_protocol.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11ws_protocol.proto\"l\n\x10WsRequestMessage\x12\x14\n\x0crequest_uuid\x18\x01 \x01(\t\x12\x14\n\x0crequest_type\x18\x02 \x01(\r\x12\x0f\n\x07session\x18\x03 \x01(\t\x12\r\n\x05route\x18\x04 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\t\"8\n\x11WsResponseMessage\x12\x15\n\rresponse_uuid\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"-\n\x15WsUpdateRequireNotice\x12\x14\n\x0crequest_uuid\x18\x01 \x01(\t\"-\n\x13WsHeartBreakMessage\x12\x16\n\x0eheart_break_id\x18\x01 \x01(\rb\x06proto3')



_WSREQUESTMESSAGE = DESCRIPTOR.message_types_by_name['WsRequestMessage']
_WSRESPONSEMESSAGE = DESCRIPTOR.message_types_by_name['WsResponseMessage']
_WSUPDATEREQUIRENOTICE = DESCRIPTOR.message_types_by_name['WsUpdateRequireNotice']
_WSHEARTBREAKMESSAGE = DESCRIPTOR.message_types_by_name['WsHeartBreakMessage']
WsRequestMessage = _reflection.GeneratedProtocolMessageType('WsRequestMessage', (_message.Message,), {
  'DESCRIPTOR' : _WSREQUESTMESSAGE,
  '__module__' : 'ws_protocol_pb2'
  # @@protoc_insertion_point(class_scope:WsRequestMessage)
  })
_sym_db.RegisterMessage(WsRequestMessage)

WsResponseMessage = _reflection.GeneratedProtocolMessageType('WsResponseMessage', (_message.Message,), {
  'DESCRIPTOR' : _WSRESPONSEMESSAGE,
  '__module__' : 'ws_protocol_pb2'
  # @@protoc_insertion_point(class_scope:WsResponseMessage)
  })
_sym_db.RegisterMessage(WsResponseMessage)

WsUpdateRequireNotice = _reflection.GeneratedProtocolMessageType('WsUpdateRequireNotice', (_message.Message,), {
  'DESCRIPTOR' : _WSUPDATEREQUIRENOTICE,
  '__module__' : 'ws_protocol_pb2'
  # @@protoc_insertion_point(class_scope:WsUpdateRequireNotice)
  })
_sym_db.RegisterMessage(WsUpdateRequireNotice)

WsHeartBreakMessage = _reflection.GeneratedProtocolMessageType('WsHeartBreakMessage', (_message.Message,), {
  'DESCRIPTOR' : _WSHEARTBREAKMESSAGE,
  '__module__' : 'ws_protocol_pb2'
  # @@protoc_insertion_point(class_scope:WsHeartBreakMessage)
  })
_sym_db.RegisterMessage(WsHeartBreakMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WSREQUESTMESSAGE._serialized_start=21
  _WSREQUESTMESSAGE._serialized_end=129
  _WSRESPONSEMESSAGE._serialized_start=131
  _WSRESPONSEMESSAGE._serialized_end=187
  _WSUPDATEREQUIRENOTICE._serialized_start=189
  _WSUPDATEREQUIRENOTICE._serialized_end=234
  _WSHEARTBREAKMESSAGE._serialized_start=236
  _WSHEARTBREAKMESSAGE._serialized_end=281
# @@protoc_insertion_point(module_scope)
